In [1]:
import pandas as pd
import numpy as np
import folium
from folium import Marker
from folium.plugins import MarkerCluster

In [2]:
df = pd.read_csv('C:/Users/user/Desktop/문정원/koreagram_2021_2022_final.csv',encoding='cp949')
df.head()

,content,place_final,place,place_content,대상여부,date,year,month,like,tags,카카오위치명,경도,위도,count
0,by travelaashley Nighttime tours to one of Se...,Gyeongbokgung,Gyeongbokgung,NaN,2,2022-09-01,2022,9,0,"['#seoulbyme', '#jongno.??', '#korea_attractio...",경복궁,126.976897,37.577609,47.0
1,Just a few more pics of Gyeongbokgung Palace i...,경복궁 - Gyeongbokgung Palace,경복궁 - Gyeongbokgung Palace,NaN,2,2022-08-09,2022,8,78,"['#korealife', '#korealandscape', '#koreatrip'...",경복궁,126.976897,37.577609,47.0
2,I never got to explore all the grounds at Gyeo...,경복궁 - Gyeongbokgung Palace,경복궁 - Gyeongbokgung Palace,NaN,2,2022-08-08,2022,8,84,"['#korealife', '#korealandscape', '#koreatrip'...",경복궁,126.976897,37.577609,47.0
3,Love the palaces in Seoul #gyeongbokgung #potd...,경복궁,경복궁,NaN,2,2022-07-26,2022,7,0,"['#gyeongbokgung', '#potd', '#seoul', '#koreab...",경복궁,126.976897,37.577609,47.0
4,I was going to tell a time traveling joke but...,경복궁,경복궁,NaN,2,2022-07-24,2022,7,0,"['#경복궁', '#seoul', '#gyeonbokgungpalace', '#po...",경복궁,126.976897,37.577609,47.0

In [3]:
df2 = df[df['대상여부']== 2]
df2.head()

,content,place_final,place,place_content,대상여부,date,year,month,like,tags,카카오위치명,경도,위도,count
0,by travelaashley Nighttime tours to one of Se...,Gyeongbokgung,Gyeongbokgung,NaN,2,2022-09-01,2022,9,0,"['#seoulbyme', '#jongno.??', '#korea_attractio...",경복궁,126.976897,37.577609,47.0
1,Just a few more pics of Gyeongbokgung Palace i...,경복궁 - Gyeongbokgung Palace,경복궁 - Gyeongbokgung Palace,NaN,2,2022-08-09,2022,8,78,"['#korealife', '#korealandscape', '#koreatrip'...",경복궁,126.976897,37.577609,47.0
2,I never got to explore all the grounds at Gyeo...,경복궁 - Gyeongbokgung Palace,경복궁 - Gyeongbokgung Palace,NaN,2,2022-08-08,2022,8,84,"['#korealife', '#korealandscape', '#koreatrip'...",경복궁,126.976897,37.577609,47.0
3,Love the palaces in Seoul #gyeongbokgung #potd...,경복궁,경복궁,NaN,2,2022-07-26,2022,7,0,"['#gyeongbokgung', '#potd', '#seoul', '#koreab...",경복궁,126.976897,37.577609,47.0
4,I was going to tell a time traveling joke but...,경복궁,경복궁,NaN,2,2022-07-24,2022,7,0,"['#경복궁', '#seoul', '#gyeonbokgungpalace', '#po...",경복궁,126.976897,37.577609,47.0

## 서울을 중심으로 위치 시각화

In [9]:
# 중심 지정
lat = 37.550
long =126.982

m = folium.Map([lat, long], zoom_start=11)

# 지도위에 표시
for i in df2.index:
    sub_lat = df2.loc[i, '위도']
    sub_long = df2.loc[i, '경도']
    
    title = df2.loc[i, '카카오위치명']
    
    #지도에 데이터 찍어서 보여주기
    folium.Marker([sub_lat, sub_long],tooltip=title,
    icon=folium.Icon(
        color='blue',
        icon_color='white',
        icon='glyphicon glyphicon-thumbs-up',
        prefix='glyphicon'
    )
                 ).add_to(m)

#m.save('seoul_mark.html')
#m

## 부산을 중심으로 위치 시각화

In [7]:
# 중심 지정
lat = 35.1856505
long =129.1

m = folium.Map([lat, long], zoom_start=11)

# 지도위에 표시
for i in df2.index:
    sub_lat = df2.loc[i, '위도']
    sub_long = df2.loc[i, '경도']
    
    title = df2.loc[i, '카카오위치명']
    
    #지도에 데이터 찍어서 보여주기
    folium.Marker([sub_lat, sub_long],tooltip=title,
    icon=folium.Icon(
        color='blue',
        icon_color='white',
        icon='glyphicon glyphicon-thumbs-up',
        prefix='glyphicon'
    )
                 ).add_to(m)


#m.save('busan_mark.html')
#m

## markercluster로 시각화하기

In [8]:
# 지도 생성하기
m = folium.Map(location=[37.5536067,126.9674308],
               zoom_start=12)
marker_cluster = MarkerCluster().add_to(m)  # 클러스터 추가하기

#마커 추가하기

for i in df2.index:
    lat = df2.loc[i, '위도']
    long = df2.loc[i, '경도']
    name = df2.loc[i,'카카오위치명']
    num = df2.loc[i, 'count']


    folium.Marker([lat, long],tooltip= name, popup='%d개'%num).add_to(marker_cluster)    

#m.save('korea_markercluster.html')
#m